<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ShopTheKafka.PaymentService-3f3e64e7-9b9e-45f9-b863-6d035cdb23f0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Confluent.Kafka" Version="13.5.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShopTheKafka.ServiceDefaults\ShopTheKafka.ServiceDefaults.csproj" />
    <ProjectReference Include="..\ShopTheKafka.Contracts\ShopTheKafka.Contracts.csproj" />
  </ItemGroup>
</Project>
